
#docker run -d --name redisinsight -p 5540:5540 redis/redisinsight:latest -v redisinsight:/data

services:
  redis:
    image: redis:latest
    container_name: 'redis_chat'
    
    ports:
      - '6379:6379'
    
    networks:
      - my-app
    
  

  redis-insight:
    image: redis/redisinsight
    container_name: 'redisinsight_chat'
    
    ports:
      - '5540:5540'
    
    networks:
      - my-app

    volumes:
      - 'redisDATA_volume_for_websocket_chat:/data'
    
    depends_on:
      - redis
    

    
  # postgresql:
  #   image: bitnami/postgresql
  #   container_name: postgresql_container

  #   ports:
  #     - '5432:5432'
    
  #   volumes:
  #     - 'postgresql_database:/bitnami/postgresql'
    
  #   networks:
  #     - my-app
    
  #   environment:
  #     - POSTGRESQL_USERNAME=${DB_USERNAME}
  #     - POSTGRESQL_PASSWORD=${DB_PASSWORD}
  #     - POSTGRESQL_DATABASE=${DB_DATABASE}
  #     - POSTGRESQL_PORT_NUMBER=${DB_PORT}
  


  # chat_websocket:
  #   image: chat_websocket:v1.0
  #   container_name: chat_websocket

  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - my-app
    



networks:
  my-app:
    driver: bridge

volumes:
  redisDATA_volume_for_websocket_chat:
  # postgresql_database:


